#' Initialize redaction rules
#'
#' Convert the output of `pidpos` to a `tibble` or csv file for editing.
#' It is intended the user changes the `To` column to define desired
#' redactions.
#'
#' @param report The `data.frame` generated by `pidpos`
#' @param path  Optional file path to write to.
#' @param include_context  Binary-flag. If True, adds a `Context` column giving a subset
#' of the sentence being redacted around the token.
#'
#' @return A tibble with columns:
#' \itemize{
#' \item `If`: The condition (sentence) under which the replacement is to be made.
#' \item `From`: The original token.
#' \item `To`: The replacement token.
#' }
#'
#' @examples
#' \dontrun{
#' example.data <- head(the_one_in_massapequa)
#' report <- pidpos(example.data, to_ignore = "speaker")
#' report_to_redaction_rules(report)
#' }
#'
#' @export
#'
#' @seealso
#' * To produce the report: [pidpos()]
#' * To automatically replace the `To` column: [auto_replace()]
#' * For redaction: [redact()]
report_to_redaction_rules <- function(report, path = NULL,
                                      include_context = FALSE) {
  if (!inherits(report, "data.frame")) {
    type_error("`report` must be a data.frame or tibble")
  }

  if (!is.null(path) && !is.character(path)) {
    type_error("`path` must be a string or NULL")
  }

  required_cols <- c("Document", "Token")
  missing <- setdiff(required_cols, names(report))
  if (length(missing) > 0) {
    validation_error(paste0("report is missing columns: ", paste(missing, collapse = ", ")))
  }

  If <- NA

  .frm <- report %>%
    mutate(
      If = .data$Document,
      #If = .data$Sentence,
      From = .data$Token,
      To = .data$Token,
      POS = if ("POS" %in% colnames(.data)) .data$POS else "",
      .keep = "none"
    ) |>
    filter(!is.na(If)) |> 
    distinct()

  if (include_context) {
    .frm <- .frm |>
      mutate(
        Context = simplify(map2(.data$If, .data$From, get_context))
      )
  }

  .frm <- structure(
    .frm,
    class = c("redaction_rules", "tbl_df", "tbl", "data.frame")
  )

  if (is.null(path)) {
    return(.frm)
  }

  readr::write_csv(.frm, path)
  .frm
}
